export default {
    defaultLanguage: 'en',

    panelsMaximumCount: 6,

    viewerMainBoardWidth: 850,
    viewerMainBoardHeight: 400,

    viewerPanelsWidth: 195,
    viewerPanelsHeight: 90,

    previewDialogPanelsWidth: 400,
    previewDialogPanelsHeight: 200,

    examinerPanelsWidth: 485,
    examinerPanelsHeight: 235,

    foregroundCategoriesAndImages: {
        'Characters_[B&W]': [
            'balloon.png',
            'banana_skin_copy.png',
            'beam_of_light_copy.png',
            'boot_copy.png',
            'cat_blur.png',
            'cat_cleaning_itself_copy.png',
            'cat_copy.png',
            'cat_running_copy.png',
            'dog.png',
            'dog_copy.png',
            'dog_happy_copy.png',
            'dog_lagging_behind_copy.png',
            'dog_looking_up_copy.png',
            'dog_pooping_copy.png',
            'lollipop_copy.png',
            'man.png',
            'man_copy.png',
            'man_looking_at_dog_copy.png',
            'man_looking_at_poop_copy.png',
            'man_looking_down_copy.png',
            'man_looking_up_copy.png',
            'man_shrugging_copy.png',
            'man_throwing_his_hands_up_copy.png',
            'man_walking.png',
            'man_walking_copy.png',
            'man_walking_the_dog_b_copy.png',
            'man_walking_the_dog_copy.png',
            'man_waving_copy.png',
            'money_copy.png',
            'poop_copy.png',
            'robot_copy.png',
            'robot_petting_copy.png',
            'robot_sad(_copy.png',
            'sock_copy.png',
            'woman.png',
            'Woman_4.png',
            'woman_looking_down_copy.png',
            'woman_looking_up_copy.png',
            'woman_offended_copy.png',
            'woman_petting_the_dog_copy.png',
            'woman_running_copy.png',
            'woman_sad_copy.png',
            'woman_shrugging_copy.png',
            'woman_walking.png',
            'woman_waving.png'

        ],
        Game_Objects: [
            'Bag.png',
            'Berries.png',
            'Book.png',
            'Bottle.png',
            'Cheese.png',
            'Cleaver.png',
            'Coin.png',
            'Egg.png',
            'Flower.png',
            'Fruit.png',
            'Key.png',
            'Knife.png',
            'Letter.png',
            'Paper.png',
            'Ring.png',
            'Untitled_1.png',
            'Untitled_2.png',
            'Untitled_3.png',
            'Untitled_4.png',
            'Untitled_5.png',
            'Untitled_6.png',
            'Untitled_7.png',
            'Untitled_8.png',
            'Untitled_9.png',
            'Untitled_10.png',
            'Untitled_11.png',
            'Untitled_12.png',
            'Untitled_13.png',
            'Untitled_14.png',
            'Untitled_15.png',
            'Untitled_16.png'
        ]
    },
    backgroundImages: [
        'Battleground2.png',
        'Battleground3.png',
        'Battleground4.png',
        'City1.png',
        'City2_pale.png',
        'City3_pale.png',
        'City4_pale.png',
        'postapocalypse2.png',
        'postapocalypse3.png',
        'postapocalypse4.png',
        'War.png',
        'War2.png',
        'War4.png',
        'background12.png',
        'background13.png',
        'background14.png',
        'background15.png'
    ]
}